eureka:
  client:
    enabled: false

spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

hystrix.command.findAllBooks.execution.isolation.thread.timeoutInMilliseconds: 3000