INSERT INTO AUTHORS (NAME) VALUES ('Mark Twain');
INSERT INTO AUTHORS (NAME) VALUES ('Luis Kerol');

INSERT INTO BOOKS (TITLE, GENRE_ID, AUTHOR_ID) VALUES ('Last Witch', 2, 2);
INSERT INTO BOOKS (TITLE, GENRE_ID, AUTHOR_ID) VALUES ('First King', 1, 2);