spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true