INSERT INTO GENRES (NAME) VALUES ('Drama');
INSERT INTO GENRES (NAME) VALUES ('Fantasy');

INSERT INTO AUTHORS (NAME) VALUES ('Mark Twain');
INSERT INTO AUTHORS (NAME) VALUES ('Luis Kerol');

INSERT INTO BOOKS (TITLE, GENRE_ID, AUTHOR_ID) VALUES ('Last Witch', 2, 2);
INSERT INTO BOOKS (TITLE, GENRE_ID, AUTHOR_ID) VALUES ('First King', 1, 2);

INSERT INTO BOOK_COMMENTS (COMMENT_TEXT, BOOK_ID) VALUES ('Абырвалг', 2);
INSERT INTO BOOK_COMMENTS (COMMENT_TEXT, BOOK_ID) VALUES ('Абырвалг2', 2);

-- test:user
INSERT INTO LIBRARY_USERS(LOGIN, PASSWORD, AUTHORITY)
 VALUES ('test', '$2a$12$hxoOh0dQGuYIB4CiC7hsbO1JW5eLrPzwioTn5HYtf5yiwD0AVYAQO', 'reader');