spring:
  batch:
    initialize-schema: always
    job.enabled: false

  shell.interactive.enabled: true

  datasource:
    initialization-mode: always
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: SpringBatchExampleDB