INSERT INTO AUTHORS (NAME) VALUES ('Mark Twain');
INSERT INTO AUTHORS (NAME) VALUES ('Luis Kerol');
INSERT INTO AUTHORS (NAME) VALUES ('Stephen King');
INSERT INTO AUTHORS (NAME) VALUES ('J. K. Rowling');

INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('Python. Last chapters', 1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('Last Witch', 2);
INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('Bugaa', 3);
INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('First King', 4);